<a href="https://colab.research.google.com/github/ZainGeeky/Predicting-Heart-Disease-through-Machine-Learning-/blob/main/Day07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
data =pd.read_csv('https://talentcocomedia.s3.amazonaws.com/ml-assets/heart-disease.csv')

In [ ]:
y = data['target']

In [ ]:
x = data.drop('target', axis =1)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=4)

x_train.shape, x_test.shape, y_train.shape, y_test.shape

((212, 13), (91, 13), (212,), (91,))

# Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
lr_model=LogisticRegression(penalty='l2', solver= 'newton-cg', C=5)

In [ ]:
lr_model.fit(x_train,y_train)

LogisticRegression(C=5, solver='newton-cg')

In [ ]:
y_pred_lr = lr_model.predict(x_test)
y_pred_lr

array([1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1])

Accuracy:

In [ ]:
from sklearn.metrics import accuracy_score
acc_lr = accuracy_score(y_pred_lr, y_test)
acc_lr

0.8021978021978022

# KNeighbors Classifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
yPredKnn = neigh.predict(x_test)

In [ ]:
yPredKnn

array([1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0])

GridsearchCV for KNN

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()


k_range = list(np.arange(1,30,1))
param_grid = dict(n_neighbors=k_range)

grid = GridSearchCV(knn, param_grid)

grid.fit(x_train, y_train)

print(grid.best_score_)
print(grid.best_params_)


0.6983388704318937
{'n_neighbors': 18}


Accuracy:

In [ ]:
accKnn = accuracy_score(yPredKnn , y_test)

In [ ]:
accKnn

0.6263736263736264

# DecisionTree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [ ]:
yPredDtc = dtc.predict(x_test)

In [ ]:
yPredDtc

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1])

GridsearchCv for Decision tree:

In [ ]:

from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier


dtree = DecisionTreeClassifier()

max_depth = list(range(1, 11))
min_samples_split = [2, 3, 4, 5]
min_samples_leaf = [1, 2, 3]
criterion = ['gini', 'entropy']
param_grid_dtree = dict(max_depth=max_depth, min_samples_split=min_samples_split, 
                  min_samples_leaf=min_samples_leaf, criterion=criterion)

grid_dtree = GridSearchCV(dtree, param_grid_dtree, cv=10, scoring='accuracy')


grid_dtree.fit(x_train, y_train)

print(grid_dtree.best_score_)
print(grid_dtree.best_params_)

0.84004329004329
{'criterion': 'gini', 'max_depth': 5, 'min_samples_leaf': 1, 'min_samples_split': 2}


Accuracy:

In [ ]:
accDtc = accuracy_score(yPredDtc , y_test)

In [ ]:
accDtc

0.7142857142857143

From the above three comparisons, we got the highest accuracy using Linear Regression.

In [ ]:
val =list(np.arange(1,20,1))
val

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
from sklearn.model_selection import GridSearchCV

model_lr = LogisticRegression(penalty='l2')

parameters = {'solver':('newton-cg', 'liblinear', 'sag', 'saga'), 'C':val}

clf_lr = GridSearchCV(model_lr, parameters)
clf_lr.fit(x_train, y_train)

In [ ]:
print(clf_lr.best_params_)

{'C': 3, 'solver': 'newton-cg'}


In [ ]:
test_pred = clf_lr.predict(x_test)

In [ ]:
acc_lr_gs = accuracy_score(test_pred, y_test)
acc_lr_gs

0.8021978021978022

# Confusion Matrix

Confusion Matrix for Linear Regression


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred_lr,y_test)

array([[27,  7],
       [11, 46]])

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred_lr ))

              precision    recall  f1-score   support

           0       0.79      0.71      0.75        38
           1       0.81      0.87      0.84        53

    accuracy                           0.80        91
   macro avg       0.80      0.79      0.79        91
weighted avg       0.80      0.80      0.80        91



Confusion Matrix for DecisionTree Classifier

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(yPredDtc,y_test)

array([[25, 13],
       [13, 40]])

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test,yPredDtc ))

              precision    recall  f1-score   support

           0       0.66      0.66      0.66        38
           1       0.75      0.75      0.75        53

    accuracy                           0.71        91
   macro avg       0.71      0.71      0.71        91
weighted avg       0.71      0.71      0.71        91



Confusion Matrix for KNN

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(yPredKnn,y_test)

array([[22, 18],
       [16, 35]])

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test,yPredKnn ))

              precision    recall  f1-score   support

           0       0.55      0.58      0.56        38
           1       0.69      0.66      0.67        53

    accuracy                           0.63        91
   macro avg       0.62      0.62      0.62        91
weighted avg       0.63      0.63      0.63        91



In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_pred,y_test)

array([[27,  7],
       [11, 46]])

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, test_pred))

              precision    recall  f1-score   support

           0       0.79      0.71      0.75        38
           1       0.81      0.87      0.84        53

    accuracy                           0.80        91
   macro avg       0.80      0.79      0.79        91
weighted avg       0.80      0.80      0.80        91



From the above Confusion Matrices, Linear Regression GridSearch CV has the maximum recall and Accuracy whereas the KNN has the least Recall and Accuracy.